### ISSUE TITLE
Default namespace for TokenSecret not applied correctly

### ISSUE THREAD

**Issue by eportet** [DopplerHQ/kubernetes-operator#15]
I tried following the sample configuration provided and the only way it worked for me was by adding a namespace of `doppler-operator-system` in the `DopplerSecret` file.

`secrets_v1alpha1_dopplersecret.yaml`
```
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-test # DopplerSecret Name
  namespace: doppler-operator-system
spec:
  tokenSecret: # Kubernetes service token secret
    name: doppler-token-secret
    # HAD TO ADD THIS FOR IT TO WORK
    namespace: doppler-operator-system
  managedSecret: # Kubernetes managed secret (will be created if does not exist)
    name: doppler-test-secret
    namespace: default # Should match the namespace of deployments that will use the secret
```

After adding that namespace the operator was able to find the Token secret and generate the ManagedSecret in the desired namespace.
