### ISSUE TITLE
Is there an option to automatically create a new config if it's not found?

### ISSUE THREAD

**Issue by MichielS-1848709** [DopplerHQ/kubernetes-operator#49]
**Issue Description:**
I'm using Doppler for production, staging, and local development. To streamline the onboarding process for new developers, it would be beneficial if the Kubernetes operator could automatically generate new configurations if they are not already present. Currently, this requires an additional step, either using the CLI or the interface.

**Suggested Approach:**
I'm currently using the following `doppler.yaml` configuration:

```yaml
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: "{{ .Values.name }}-api-doppler"
  namespace: default
spec:
  tokenSecret:
    name: "doppler-api-token-secret"
  project: api
  config: 
     name: "{{ .Values.dopplerEnv }}"
     auto: true # Automatically creates the config if not found.
  managedSecret:
    name: "{{ .Values.name }}-api-secrets"
    namespace: default
```

**Question:**
Is there an alternative approach using Kubernetes YAML files to achieve this desired behavior, without relying on the CLI or interface?
