### ISSUE TITLE
How to configure a "master token secret"

### ISSUE THREAD

**Issue by jhoelzel** [DopplerHQ/kubernetes-operator#55]
Hey guys, 
First of all thank you for the operator, we use it constantly.

Now there has come a point where we are spending more time deploying "token secrets" into the cluster than anything esle, which is especially true if you do feature deployments with kubernetes.

Is there a simple way to deploy a "token secret" with multiple DOPPLER tokens inside and use that to create other secrets?

Usercase:

1) Have a project that contains all the doppler tokens for the different configurations you deploy in kubernetes. At this point im deploying around 10 token secrets and its getting kumbersome to deploy them by hand.
2) deploy these tokens into the cluster using doppler
3) Use the deployed secret of that operation to feed other doppler configurations inside the cluster.

basically im looking for this:
``` YAML
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-backups
  namespace: doppler-operator-system
spec:
  host: https://api.doppler.com
  managedSecret:
    name: dopplersecret-staging-postgres
    namespace: postgres-staging
    type: Opaque
  resyncSeconds: 60
  tokenSecret:
    name: doppler-cluster-tokens
    **KEY**: token-backups
  verifyTLS: true
```

But maybe there is a better way which i simply cant see?

thanks

**Comment by watsonian** [comment]
@jhoelzel The recommended way to accomplish this would be to use [Service Accounts](https://docs.doppler.com/docs/service-accounts). You can give the SA access to whichever configs you're managing in Kubernetes and then a Service Account Token for it will have access to all those configs. You would then use that one token in all your `DopplerSecret` CRDs and just reference the project and config name like this:

```
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-test # DopplerSecret Name
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
  project: your-project-name-here
  config: your-config-name-here
  managedSecret:
    name: doppler-test-secret
    namespace: default
```

That said, Service Accounts are only available on the Team plan or higher. Is that a potential option for you?
