### ISSUE TITLE
[Kubernetes] imagePullSecrets: unable to deploy

### ISSUE THREAD

**Issue by jhoelzel** [DopplerHQ/kubernetes-operator#56]
Thanks again for a nice solution to our problems ;)

When deploying custom images to Kubernetes from a private image repository, an acces configuration is required.
[Link to Docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)

This secret is defined by a key called " .dockerconfigjson ". You can probably see where im going with this:

There is currently no way to deploy it with the kubernetes operator. https://docs.doppler.com/docs/kubernetes-operator

We really would appreciate a solution to this as the only secret "not dopplered" are our image pull secrets =)
The best solution is probably a Name Transformer.

Thank you!

**Comment by nmanoogian** [comment]
Hi @jhoelzel! Thanks for reaching out!

I think you might be able to use [custom types and processors](https://github.com/DopplerHQ/kubernetes-operator/blob/main/docs/custom_types_and_processors.md) to achieve this. It might look something like:

```yaml
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: my-dopplersecret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: doppler-config-secret
    namespace: default
    type: kubernetes.io/dockerconfigjson
  processors:
    DOCKER_CONFIG_JSON: # This is the name of the secret in Doppler to use for the `.dockerconfigjson` contents
      asName: .dockerconfigjson
```

Can you give this a go and let me know if it works for you?
