### ISSUE TITLE
Support custom labels on created Secret

### ISSUE THREAD

**Issue by aarguello** [DopplerHQ/kubernetes-operator#64]
### Problem

The `DopplerSecret` CRD does not have a field to set labels on the Secret it manages. This prevents me to manage ArgoCD cluster and repository credentials using Doppler because ArgoCD determines a secret's purpose based on its label, particularly `argocd.argoproj.io/secret-type: cluster | repository | repo-creds`.

### Proposal

Add a `labels` field under `managedSecret`, so that I could declare something like the following:

```
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  namespace: doppler-operator-system
  name: argocd-cluster-credentials
spec:
  tokenSecret:
    name: doppler-token-secret-argocd
  managedSecret:
    name: argocd-cluster-credentials
    namespace: argocd
    labels:
      argocd.argoproj.io/secret-type: cluster
```

Another alternative would be to replicate the labels of the `DopplerSecret` to the `Secret`.

Please let me know if you think this feature makes sense and, if it does, whether you'd like me to send a PR for it or prefer that the project maintainers handle it.

### References

- https://argo-cd.readthedocs.io/en/stable/user-guide/annotations-and-labels/#labels
- https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters
