### ISSUE TITLE
Doppler Operator fails with GRPC Liveness Probe

### ISSUE THREAD

**Issue by vvmarchenko** [DopplerHQ/kubernetes-operator#70]
We are encountering an issue with the Doppler Kubernetes Operator when using a `grpc` liveness probe in our deployment. The operator fails to reconcile the deployment due to a validation error related to the `livenessProbe` configuration.

#### Error Message
```
2024-11-14T11:30:10.154Z    ERROR   controllers.DopplerSecret   Unable to reconcile deployment  {"dopplersecret": "doppler-operator-system/my-app-secret", "error": "Failed to update deployment annotation: Deployment.apps \"my-app\" is invalid: [spec.template.spec.containers[0].livenessProbe: Required value: must specify a handler type, spec.template.spec.containers[0].readinessProbe: Required value: must specify a handler type]"}
github.com/go-logr/zapr.(*zapLogger).Error
    /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/DopplerHQ/kubernetes-operator/controllers.(*DopplerSecretReconciler).ReconcileDeploymentsUsingSecret.func1
    /workspace/controllers/dopplersecret_controller_deployments.go:67
```

#### Context
Our deployment configuration includes a `grpc` liveness probe:

```yaml
livenessProbe:
  grpc:
    port: 50051
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
```

Despite running on **Kubernetes 1.30**, which supports `grpc` liveness probes, the Doppler Operator fails to update the deployment, likely due to an internal validation that does not recognize the `grpc` probe type.
