### ISSUE TITLE
Failed to restart Pods with sidecar containers

### ISSUE THREAD

**Issue by lucassus** [DopplerHQ/kubernetes-operator#81]
I have the following deployment that uses a sidecar container (https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/):

```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ***
    annotations:
      secrets.doppler.com/reload: "true"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: web
        app.kubernetes.io/instance: release-name
    template:
      spec:
        serviceAccountName: ***
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        initContainers:
          # Native sidecar container, see https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/
          - name: haproxy-redis-sidecar
            image: haproxy:3.0.5
            imagePullPolicy: IfNotPresent
            restartPolicy: Always
            args: ["-V", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
            volumeMounts:
              - name: haproxy-redis-cfg
                mountPath: /usr/local/etc/haproxy/haproxy.cfg
            readinessProbe:
              exec:
                command: ["cat", "/dev/null"]
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 3
        containers:
        - name: ab
          envFrom:
            # Load environment variables from the Doppler
            - secretRef:
                name: ***
          ....
```

For some reason Doppler Operator can't sync secrets for this deployment. 
I have lots of errors like:

```
2025-01-20T16:16:34.906Z	ERROR	controllers.DopplerSecret	Unable to reconcile deployment	{"dopplersecret": "doppler-operator-system/***", "error": "Failed to update deployment annotation: Deployment.apps \"web-***\" is invalid: spec.template.spec.initContainers[0].readinessProbe: Forbidden: may not be set for init containers without restartPolicy=Always"}
```

**Comment by lucassus** [comment]
@nmanoogian This issue looks similar https://github.com/Azure/azure-workload-identity/issues/1312
Maybe simple dependency upgrade will do the job?

**Comment by nmanoogian** [comment]
Ah, good find -- I think you're right. We'll try bumping the Kubernetes dependencies and controller runtime.

**Comment by david-gang** [comment]
we use the google cloud sql proxy with the sidecar pattern as recommended by google: https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#run_the_in_a_sidecar_pattern

unfortunately the doppler reload does not work anymore. I would really appreciate if this could be handled soon. Additionally are there any workarounds for this issue, instead of manually restarting the deployment?

**Comment by lucassus** [comment]
Yes, there is a workaround. 

You can use the Doppler Operator to pull secrets and store them in Kubernetes Secrets, then use [stakater/Reloader](https://github.com/stakater/Reloader) to trigger reloads whenever those secrets change.

```yaml
# ...
annotations:
  # A workaround for broken Doppler operator, until https://github.com/DopplerHQ/kubernetes-operator/issues/81 is solved
  secrets.doppler.com/reload: "false"
  reloader.stakater.com/auto: "true"

# ...
envFrom:
  # Load environment variables from the secrets controlled by Doppler
  - secretRef:
      name: {{ .Release.Namespace }}-secret
```

We use it in prod and it works like a charm ;)
